import { useMutation, useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { api } from "../api";
const days = ["D", "S", "T", "Q", "Q", "S", "S"];
const equipment = [["peso_corporal","Peso corporal"],["halter","Halteres"],["anilha","Anilhas"],["barra","Barra"],["cabo","Cabo"],["maquina","Máquinas"],["elastico","Elástico"]];
const muscles = [["peitoral","Peitoral"],["costas","Costas"],["ombro","Ombros"],["biceps","Bíceps"],["triceps","Tríceps"],["core","Core"],["gluteos","Glúteos"],["pernas","Pernas"]];
export function MetaPage() {
  const existing = useQuery({ queryKey: ["meta"], queryFn: () => api<any>("/meta") });
  const memberships = useQuery({ queryKey: ["memberships"], queryFn: () => api<any>("/memberships") });
  const [form, setForm] = useState<any>({ goal:"mais_disposto", level:"iniciante", trainingDays:[1,3,5], durationMinutes:"45", location:"academia", equipment:["peso_corporal","halter"], weightKg:70, heightCm:170, age:30, sex:"nao_informar", priorityMuscles:[], intensity:"moderada", injuries:[] });
  const bmi = useMemo(() => (form.weightKg / ((form.heightCm/100) ** 2)).toFixed(1), [form.weightKg, form.heightCm]);
  const save = useMutation({ mutationFn: () => api<any>("/meta", { method:"PUT", body:JSON.stringify(form) }) });
  const toggle = (key:string, value:any, max=99) => setForm((f:any) => ({...f,[key]:f[key].includes(value)?f[key].filter((v:any)=>v!==value):f[key].length<max?[...f[key],value]:f[key]}));
  return <section className="page meta-page"><div className="page-title"><div><span className="eyebrow">PERSONALIZAÇÃO</span><h1>Sua meta</h1></div><div className="bmi"><span>IMC</span><strong>{bmi}</strong></div></div>
    <div className="form-section"><h2>Como você quer se sentir amanhã?</h2><select value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})}><option value="mais_disposto">Mais disposto</option><option value="mais_bonito">Mais bonito</option><option value="mais_forte">Mais forte</option><option value="mais_leve">Mais leve</option><option value="mais_saudavel">Mais saudável</option><option value="menos_estressado">Menos estressado</option></select></div>
    <div className="form-grid"><label>Nível<select value={form.level} onChange={e=>setForm({...form,level:e.target.value})}><option value="iniciante">Iniciante</option><option value="intermediario">Intermediário</option><option value="avancado">Avançado</option></select></label><label>Duração<select value={form.durationMinutes} onChange={e=>setForm({...form,durationMinutes:e.target.value})}>{["30","45","60","75","90"].map(v=><option key={v} value={v}>{v} min</option>)}</select></label></div>
    <div className="form-section"><h2>Dias de treino</h2><div className="day-picker">{days.map((d,i)=><button key={i} className={form.trainingDays.includes(i)?"selected":""} onClick={()=>toggle("trainingDays",i)}>{d}</button>)}</div></div>
    <div className="form-grid three"><label>Peso<select value={form.weightKg} onChange={e=>setForm({...form,weightKg:Number(e.target.value)})}>{Array.from({length:221},(_,i)=>i+30).map(v=><option key={v}>{v}</option>)}</select></label><label>Altura<select value={form.heightCm} onChange={e=>setForm({...form,heightCm:Number(e.target.value)})}>{Array.from({length:111},(_,i)=>i+120).map(v=><option key={v}>{v}</option>)}</select></label><label>Idade<select value={form.age} onChange={e=>setForm({...form,age:Number(e.target.value)})}>{Array.from({length:87},(_,i)=>i+14).map(v=><option key={v}>{v}</option>)}</select></label></div>
    <div className="form-section"><h2>Equipamentos disponíveis</h2><div className="choice-grid">{equipment.map(([v,l])=><button key={v} className={form.equipment.includes(v)?"selected":""} onClick={()=>toggle("equipment",v)}>{l}</button>)}</div></div>
    <div className="form-section"><h2>Músculos prioritários <small>até 3</small></h2><div className="choice-grid">{muscles.map(([v,l])=><button key={v} className={form.priorityMuscles.includes(v)?"selected":""} onClick={()=>toggle("priorityMuscles",v,3)}>{l}</button>)}</div></div>
    <div className="form-grid"><label>Local<select value={form.location} onChange={e=>setForm({...form,location:e.target.value})}><option value="academia">Academia</option><option value="casa">Casa</option><option value="ambos">Ambos</option></select></label><label>Intensidade<select value={form.intensity} onChange={e=>setForm({...form,intensity:e.target.value})}><option value="leve">Leve</option><option value="moderada">Moderada</option><option value="intensa">Intensa</option></select></label></div>
    <div className="form-section"><h2>Lesões ou limitações?</h2><div className="choice-grid">{["ombro","cotovelo","punho","coluna_lombar","quadril","joelho","tornozelo"].map(region=><button key={region} className={form.injuries.some((x:any)=>x.region===region)?"selected danger":""} onClick={()=>setForm((f:any)=>({...f,injuries:f.injuries.some((x:any)=>x.region===region)?f.injuries.filter((x:any)=>x.region!==region):[...f.injuries,{region,severity:"leve",status:"recuperacao",medicallyCleared:true}]}))}>{region.replace("_"," ")}</button>)}</div><p className="hint">Dor aguda ou lesão grave sem liberação bloqueará a geração por segurança.</p></div>
    {!!memberships.data?.memberships?.length&&<div className="form-section"><h2>Personais com acesso completo</h2>{memberships.data.memberships.map((m:any)=><div className="consent-row" key={m.id}><span>{m.tenantName}</span><button onClick={async()=>{await api(`/memberships/${m.id}/revoke`,{method:"POST"});memberships.refetch()}}>Revogar acesso</button></div>)}</div>}
    {save.error&&<p className="error">{save.error.message}</p>}<button className="primary sticky-action" disabled={save.isPending} onClick={()=>save.mutate()}>{save.isPending?"Montando seu plano...":"Salvar e gerar meu treino"}</button>
  </section>;
}
